version:  '3.3'
services:
    mysql:
        image: mysql:5.7
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: auction_portal_db
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - '3306:3306'

    adminer:
        image: adminer
        restart: always
        ports:
            - '8080:8080'

    nginx:
        image: nginx:1.19.0-alpine
        restart: on-failure
        volumes:
            - './apps/auction-portal-app/web/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8084:80'
        depends_on: 
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes: 
            - './apps/auction-portal-app/:/usr/src/app'
        restart: on-failure
        user: 1000:1000