index:
  path: /
  defaults: { _controller: AppBundle:Default:index }

register_user:
  path: /registro.html
  defaults: { _controller: UserBundle:User:register }

login:
  path: /login
  defaults: { _controller: UserBundle:User:login }

logout:
  path: /logout

create_auction:
  path: /subasta/crear.html
  defaults: { _controller: AuctionBundle:Auction:createAuction }

edit_auction:
  path: /subasta/editar/{id}.html
  defaults: { _controller: AuctionBundle:Auction:editAuction }

remove_auction:
  path: /subasta/borrar/{id}.html
  defaults: { _controller: AuctionBundle:Auction:removeAuction }

list_auction:
  path: /lista-subastas.html
  defaults: { _controller: AuctionBundle:Auction:auctionList }

set_bid:
  path: /puja/nueva/{auctionId}.html
  defaults: { _controller: AuctionBundle:Bid:setBid }

my_bids:
  path: /puja/mis-pujas.html
  defaults: { _controller: AuctionBundle:Bid:viewBidsByUser }

cancel_bid:
  path: /puja/cancelar/{idBid}.html
  defaults: { _controller: AuctionBundle:Bid:cancelBid }